/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        String inputFilePathToImage = "./app/src/main/resources/snape.bmp";
        String outputFilePathToFolder = "./app/src/main/resources/newImages";
        String transformEdge = "Edged Snape ";
        String transformNegative = "Negative Snape";
        String transformGrey = "Grey Snape";
        String transformVer="Vertical Snape";
        String transformHor="Horizontal Snape";
        String transformBlur="blur Snape";


        Bitmap imageOne = new Bitmap(inputFilePathToImage, outputFilePathToFolder, transformEdge);
        Bitmap imageTwo = new Bitmap(inputFilePathToImage, outputFilePathToFolder, transformNegative);
        Bitmap imageThree = new Bitmap(inputFilePathToImage, outputFilePathToFolder, transformGrey);
        Bitmap imageFour = new Bitmap(inputFilePathToImage, outputFilePathToFolder, transformVer);
        Bitmap imageFive = new Bitmap(inputFilePathToImage, outputFilePathToFolder, transformHor);
        Bitmap imageSix = new Bitmap(inputFilePathToImage, outputFilePathToFolder, transformBlur);

        imageOne.edgeColor();
        imageTwo.NegativeColor();
        imageThree.transformGrey();
        imageFour.reverseImageVertically();
        imageFive.reverseImageHorizontally();
        imageSix.blur();
        }
}
